### PR TITLE
Dev io simple

### PR DESCRIPTION
**Pull request by adriansinger87**

### CODE REVIEW

**Review by tripoder — COMMENTED** [review]
Moved Parsers from IReadable/IWritable to concrete implementation in commit 348778c8.

**Review by tripoder — COMMENTED** [review]
Moved Parsers from IReadable/IWritable to concrete implementation in commit 348778c8.

**Comment by adriansinger87** [comment]
Hi @tripoder, I think the branch is now ready to get merged on the main branch. I have updated the following things:

- cleanup on the IReadable and IWritable generic parameters,
- NuGet package information updated for all affected assemblies (mostly all, because of the refactorings due to the sonarLint suggestions),
- Minor improvements on CsvStorageSetup constrcutor and
- some code cleanup

When you hit the approvement you can also directly finish the merge process

**Review by tripoder — APPROVED** [review]
:-)

**Pull request merged**
